export default [
 
  {
    id: "TD-001",
    client: "Acme Construction",
    type: "Residential",
    due: "2025-08-05",
    status: "NEW",
    boqUploaded: false,
    value: 0,


  },
  {
    id: "TD-002",
    client: "Skyline Group",
    type: "Commercial",
    due: "2025-08-08",
    status: "UNDER_REVIEW",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-003",
    client: "BuildCo Ltd.",
    type: "Industrial",
    due: "2025-08-10",
    status: "PRICED",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-004",
    client: "Greenfield Holdings",
    type: "Mixed-Use",
    due: "2025-08-12",
    status: "SENT",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-005",
    client: "UrbanCore Developments",
    type: "Residential",
    due: "2025-08-15",
    status: "NEW",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-006",
    client: "PrimeBuild Inc.",
    type: "Commercial",
    due: "2025-08-18",
    status: "UNDER_REVIEW",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-007",
    client: "FutureConstruct",
    type: "Industrial",
    due: "2025-08-20",
    status: "PRICED",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-008",
    client: "Evergreen Estates",
    type: "Mixed-Use",
    due: "2025-08-22",
    status: "SENT",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-009",
    client: "NovaBuild Partners",
    type: "Residential",
    due: "2025-08-25",
    status: "NEW",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-010",
    client: "NextGen Infrastructure",
    type: "Commercial",
    due: "2025-08-28",
    status: "UNDER_REVIEW",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-011",
    client: "Blue Horizon Ltd.",
    type: "Industrial",
    due: "2025-08-30",
    status: "PRICED",
    boqUploaded: false,
    value: 0,
  },
  {
    id: "TD-012",
    client: "Cedar Ridge Holdings",
    type: "Mixed-Use",
    due: "2025-09-01",
    status: "SENT",
    boqUploaded: false,
    value: 0,
  },
];
